name: Publish

on:
  push:
    branches:
      - "*"

#on:
#  pull_request:
#    branches:
#      - main

jobs:
  tests:
    name: Run tests on k8s
    runs-on: ubuntu-latest
    steps:
      - name: Install app
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm --version


          wget https://github.com/SomeBlackMagic/helm-assistant/releases/latest/download/helm-assistant-linux-amd64
          chmod +x helm-assistant-linux-amd64
          mv helm-assistant-linux-amd64 /usr/local/bin/helm-assistant
          
          helm-assistant version
          
          

#      - uses: balchua/microk8s-actions@v0.3.2
#        with:
#          channel: '1.26/stable'
#          #addons: '["dns", "rbac", "hostpath-storage"]'
#
#
#      - name: Test MicroK8s
#        run: |
#          kubectl get no
#          kubectl get pods -A -o wide

