name: Publish

#on:
#  push:
#    branches:
#      - "*"

on:
  pull_request:
    branches:
      - master

#  push:
#    tags:
#      - '*'

jobs:
  tests:
    name: Run tests on k8s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: balchua/microk8s-actions@v0.3.2
        with:
          channel: '1.26/stable'
#          addons: '["dns", "rbac", "hostpath-storage"]'
      - name: Test MicroK8s
        id: myactions
        run: |
          kubectl get no
          kubectl get pods -A -o wide

